apiVersion: apps/v1
kind: Deployment
metadata:
  name: yjnmdtns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yjnmdtns
  template:
    metadata:
      labels:
        app: yjnmdtns
    spec:
      containers:
      - image: okteto.dev/yjnmdtns:latest
        name: yjnmdtns
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "343ff181-900b-4778-a4a3-f790c3b5a386"
        - name: Vless_Path
          value: "/jkduij897"
        - name: Vmess_UUID
          value: "343ff181-900b-4778-a4a3-f790c3b5a386"
        - name: Vmess_Path
          value: "/uiytre345"
        - name: Share_Path
          value: "/v2link"
